baseURL = "https://raditian-hugo.radity.com/"
languageCode = "es"
theme = "raditian-free-hugo-theme"

# Plugins
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "css/main.css"
  [[params.plugins.css]]
  URL = "css/rad-icons.css"
  [[params.plugins.css]]
  URL = "css/custom.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "js/rad-animations.js"
  [[params.plugins.js]]
  URL = "js/sticky-header.js"
  [[params.plugins.js]]
  URL = "js/library/fontfaceobserver.js"


# navigation
[menu]

  [[menu.header]]
  name = "Quienes somos"
  URL = "#"
  weight = 2

  [[menu.header]]
  name = "Servicios"
  URL = "#"
  weight = 3

  [[menu.header]]
  name = "Contactanos"
  URL = "#"
  weight = 4

  [[menu.header]]
  name = "Misión"
  URL = "#"
  weight = 4

  [[menu.header]]
  name = "Visión"
  URL = "#"
  weight = 4

  [[menu.header]]
  name = "Objetivos"
  URL = "#"
  weight = 4

  [[menu.header]]
  name = "Nosotros"
  URL = "#"
  weight = 5

  [[menu.footer]]
  name = "Quien soy"
  URL = "#about"
  weight = 2

  [[menu.footer]]
  name = "Portfolio"
  URL = "#portfolio"
  weight = 3

  [[menu.footer]]
  name = "Contactame"
  URL = "#contact"
  weight = 4


[params]

  sections = ["showcase", "about", "education", "experience", "client-and-work", "testimonial", "contact", "newsletter"]

  googleTagManagerID = "GTM-000000" # Google Analytics works with Google Tag Manager

  [params.logo]
    text1 = "Colman"
    text2 = "Web Site"

  [params.footer]
      copyright = "© COLMAN. Reservados todos los derechos."
      [params.footer.radity_logo]
        x = "img/general/design-and-code-radity.png"
        _2x = "img/general/design-and-code-radity@2x.png"
        alt = "Design & Code - Radity"